package trading.quantity

/**
 * Marker for dimensions carried by exact and grid quantities.
 *
 * The dimension algebra is the free abelian group generated by atomic dimensions. [[One]] is its identity, while
 * [[Times]], [[Inverse]], and [[Divide]] are public expression constructors preserved by dimension-changing arithmetic.
 *
 * Declared tuple order and public expression spelling preserve useful operand structure but are not mathematical
 * identity. [[SameDimension]] derives static equivalence modulo permutation or recovers it from checked runtime
 * witnesses; [[DimKey]] remains the authoritative arbitrary-precision runtime representation.
 */
sealed trait Dim

/** A declared canonical sequence of unique singleton-key powers. */
sealed trait Canonical[Entries <: Tuple] extends Dim

/** An atomic type-level dimension identified by one stable singleton key. */
type Atom[K <: Singleton] = Canonical[Power[K, 1] *: EmptyTuple]

/** The dimensionless multiplicative identity. */
type One = Canonical[EmptyTuple]

/** A public product expression preserved by dimension-changing arithmetic. */
sealed trait Times[A <: Dim, B <: Dim] extends Dim

/** A public inverse expression preserved by witness algebra and reciprocal operations. */
sealed trait Inverse[A <: Dim] extends Dim

/** The public quotient expression `A / B`. */
type Divide[A <: Dim, B <: Dim] = Times[A, Inverse[B]]

/** A dimensionless exact quantity. */
type Ratio = Quantity[One]

/** An exact conversion factor oriented from `From` to `To`, represented by the public `To / From` expression. */
type Rate[From <: Dim, To <: Dim] = Quantity[Divide[To, From]]

/** Constructs exact conversion rates from authoritative source and target dimension witnesses. */
object Rate:

  def apply[F <: Dim, T <: Dim](
    f: DimRef[F],
    t: DimRef[T],
    c: Rational
  ): Rate[F, T] =
    Quantity(DimRef.divide(t, f), c)

  /** The identity rate, constructed only from an authoritative dimension witness. */
  def identity[D <: Dim](
    d: DimRef[D]
  ): Rate[D, D] =
    apply(d, d, Rational.one)
end Rate
