package trading.quantity

/**
 * Marker for dimensions carried by exact and grid quantities.
 *
 * The dimension algebra is the free abelian group generated by atomic dimensions. [[One]] is its identity, [[Times]] is
 * its product, [[Inverse]] supplies inverses, and [[Divide]] is product with an inverse. Dimension expressions built
 * from those type constructors prevent incompatible values from being combined at compile time.
 *
 * Scala preserves the shape of a type expression rather than normalizing the group laws: for example,
 * `Times[A, Inverse[A]]` is not the same Scala type as `One`. [[DimensionKey]] supplies the canonical group element at
 * runtime, [[DimRef]] connects an expression type to that element, and [[SameDimension]] recovers checked equivalence
 * between differently shaped expressions.
 */
trait Dimension

/** The dimensionless multiplicative identity. */
sealed trait One extends Dimension

/** An atomic type-level dimension labelled by `K`. */
sealed trait Atom[K] extends Dimension

/** The product of dimensions `A` and `B`. */
sealed trait Times[A <: Dimension, B <: Dimension] extends Dimension

/** The multiplicative inverse of dimension `A`. */
sealed trait Inverse[A <: Dimension] extends Dimension

/** The quotient dimension `A / B`. */
type Divide[A <: Dimension, B <: Dimension] = Times[A, Inverse[B]]

/** A dimensionless exact quantity. */
type Ratio = Quantity[One]

/** An exact conversion factor whose dimension is `To / From`. */
type Rate[From <: Dimension, To <: Dimension] = Quantity[Divide[To, From]]

/** Constructs exact conversion rates from authoritative source and target dimension witnesses. */
object Rate:

  def apply[F <: Dimension, T <: Dimension](f: DimRef[F], t: DimRef[T], c: Rational): Rate[F, T] =
    Quantity(DimRef.divide(t, f), c)

  /** The identity rate, constructed only from an authoritative dimension witness. */
  def identity[D <: Dimension](d: DimRef[D]): Rate[D, D] =
    apply(d, d, Rational.one)
