package trading.quantity

/**
 * Marker for dimensions carried by exact and grid quantities.
 *
 * The dimension algebra is the free abelian group generated by atomic dimensions. [[One]] is its identity, while
 * [[Times]], [[Inverse]], and [[Divide]] remain source-level expression constructors. Arithmetic normalizes those
 * expressions to canonical [[Dim]] tuples, combining equal singleton keys and removing zero exponents.
 *
 * Normalized tuple order preserves useful operand order but is not mathematical identity. [[SameDimension]] derives
 * static equivalence modulo permutation or recovers it from checked runtime witnesses; [[DimensionKey]] remains the
 * authoritative arbitrary-precision runtime representation.
 */
sealed trait Dimension

/** A canonical sequence of unique singleton-key powers. */
sealed trait Dim[Entries <: Tuple] extends Dimension

/** An atomic type-level dimension identified by one stable singleton key. */
type Atom[K <: Singleton] = Dim[Power[K, 1] *: EmptyTuple]

/** The dimensionless multiplicative identity. */
type One = Dim[EmptyTuple]

/** A source-level product expression; arithmetic results use canonical [[Dim]] values. */
sealed trait Times[A <: Dimension, B <: Dimension] extends Dimension

/** A source-level inverse expression; arithmetic results use canonical [[Dim]] values. */
sealed trait Inverse[A <: Dimension] extends Dimension

/** The quotient dimension `A / B`. */
type Divide[A <: Dimension, B <: Dimension] = Times[A, Inverse[B]]

/** A dimensionless exact quantity. */
type Ratio = Quantity[One]

/** An exact conversion factor whose dimension is `To / From`. */
type Rate[From <: Dimension, To <: Dimension] = Quantity[Divide[To, From]]

/** Constructs exact conversion rates from authoritative source and target dimension witnesses. */
object Rate:

  def apply[F <: Dimension, T <: Dimension](
    f: DimRef[F],
    t: DimRef[T],
    c: Rational
  )(using operation: Normalize[Divide[T, F]]
  ): Rate[F, T] =
    val normalized: DimRef[operation.Out] = DimRef.divide(t, f)(using operation)
    Quantity(normalized, c).asInstanceOf[Rate[F, T]]

  /** The identity rate, constructed only from an authoritative dimension witness. */
  def identity[D <: Dimension](
    d: DimRef[D]
  )(using
    operation: Normalize[Divide[D, D]]
  ): Rate[D, D] =
    apply(d, d, Rational.one)(using operation)
end Rate
